{
	"name": "MultiRoomMediaVolume",
	"speakableName": "Multi Room Media Volume",
	"version": "0.0.1",
	"icon": "fab fa-battle-net",
	"category": "entertainment",
	"author": "poulsp",
	"maintainers": [],
	"desc": "Manage volume in the synchronous multiroom audio system.",
	"aliceMinVersion": "1.0.0-b5",
	"pipRequirements": [],
	"systemRequirements": [
		""
	],
	"conditions": {
		"lang": [
			"en"
		],
		"online": true,
		"asrArbitraryCapture": true
	}
}
